# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: datarunapi
services:
  app:
    env_file:
      - .env
    image: datarunapi
    container_name: datarunapi-app
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
#    volumes:
#      - ../../target/data-run-api-0.0.1-SNAPSHOT.jar:/app/data-run-api-0.0.1-SNAPSHOT.jar
#    command: ["java", "-jar", "/app/data-run-api-0.0.1-SNAPSHOT.jar"]
    ports:
      - 8080:8080
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      postgresql:
        condition: service_healthy
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
