package org.nmcpye.datarun.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CampaignTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCampaignTypeAllPropertiesEquals(CampaignType expected, CampaignType actual) {
        assertCampaignTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertCampaignTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCampaignTypeAllUpdatablePropertiesEquals(CampaignType expected, CampaignType actual) {
        assertCampaignTypeUpdatableFieldsEquals(expected, actual);
        assertCampaignTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCampaignTypeAutoGeneratedPropertiesEquals(CampaignType expected, CampaignType actual) {
        assertThat(expected)
            .as("Verify CampaignType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCampaignTypeUpdatableFieldsEquals(CampaignType expected, CampaignType actual) {
        assertThat(expected)
            .as("Verify CampaignType relevant properties")
            .satisfies(e -> assertThat(e.getCampaignType()).as("check campaignType").isEqualTo(actual.getCampaignType()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCampaignTypeUpdatableRelationshipsEquals(CampaignType expected, CampaignType actual) {}
}
