package org.nmcpye.datarun.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ChvSessionsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChvSessionsAllPropertiesEquals(ChvSessions expected, ChvSessions actual) {
        assertChvSessionsAutoGeneratedPropertiesEquals(expected, actual);
        assertChvSessionsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChvSessionsAllUpdatablePropertiesEquals(ChvSessions expected, ChvSessions actual) {
        assertChvSessionsUpdatableFieldsEquals(expected, actual);
        assertChvSessionsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChvSessionsAutoGeneratedPropertiesEquals(ChvSessions expected, ChvSessions actual) {
        assertThat(expected)
            .as("Verify ChvSessions auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChvSessionsUpdatableFieldsEquals(ChvSessions expected, ChvSessions actual) {
        assertThat(expected)
            .as("Verify ChvSessions relevant properties")
            .satisfies(e -> assertThat(e.getUid()).as("check uid").isEqualTo(actual.getUid()))
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getSessionDate()).as("check sessionDate").isEqualTo(actual.getSessionDate()))
            .satisfies(e -> assertThat(e.getSubject()).as("check subject").isEqualTo(actual.getSubject()))
            .satisfies(e -> assertThat(e.getSessions()).as("check sessions").isEqualTo(actual.getSessions()))
            .satisfies(e -> assertThat(e.getPeople()).as("check people").isEqualTo(actual.getPeople()))
            .satisfies(e -> assertThat(e.getComment()).as("check comment").isEqualTo(actual.getComment()))
            .satisfies(e -> assertThat(e.getStartEntryTime()).as("check startEntryTime").isEqualTo(actual.getStartEntryTime()))
            .satisfies(e -> assertThat(e.getDeleted()).as("check deleted").isEqualTo(actual.getDeleted()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChvSessionsUpdatableRelationshipsEquals(ChvSessions expected, ChvSessions actual) {
        assertThat(expected)
            .as("Verify ChvSessions relationships")
            .satisfies(e -> assertThat(e.getTeam()).as("check team").isEqualTo(actual.getTeam()));
    }
}
