package org.nmcpye.datarun.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TeamFormAccessAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeamFormAccessAllPropertiesEquals(TeamFormAccess expected, TeamFormAccess actual) {
        assertTeamFormAccessAutoGeneratedPropertiesEquals(expected, actual);
        assertTeamFormAccessAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeamFormAccessAllUpdatablePropertiesEquals(TeamFormAccess expected, TeamFormAccess actual) {
        assertTeamFormAccessUpdatableFieldsEquals(expected, actual);
        assertTeamFormAccessUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeamFormAccessAutoGeneratedPropertiesEquals(TeamFormAccess expected, TeamFormAccess actual) {
        assertThat(expected)
            .as("Verify TeamFormAccess auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeamFormAccessUpdatableFieldsEquals(TeamFormAccess expected, TeamFormAccess actual) {
        assertThat(expected)
            .as("Verify TeamFormAccess relevant properties")
            .satisfies(e -> assertThat(e.getUid()).as("check uid").isEqualTo(actual.getUid()))
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getSessionDate()).as("check sessionDate").isEqualTo(actual.getSessionDate()))
            .satisfies(e -> assertThat(e.getSubject()).as("check subject").isEqualTo(actual.getSubject()))
            .satisfies(e -> assertThat(e.getSessions()).as("check sessions").isEqualTo(actual.getSessions()))
            .satisfies(e -> assertThat(e.getPeople()).as("check people").isEqualTo(actual.getPeople()))
            .satisfies(e -> assertThat(e.getComment()).as("check comment").isEqualTo(actual.getComment()))
            .satisfies(e -> assertThat(e.getDeleted()).as("check deleted").isEqualTo(actual.getDeleted()))
            .satisfies(e -> assertThat(e.getStartEntryTime()).as("check startEntryTime").isEqualTo(actual.getStartEntryTime()))
            .satisfies(e -> assertThat(e.getFinishedEntryTime()).as("check finishedEntryTime").isEqualTo(actual.getFinishedEntryTime()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeamFormAccessUpdatableRelationshipsEquals(TeamFormAccess expected, TeamFormAccess actual) {}
}
