package org.nmcpye.datarun.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TeamAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeamAllPropertiesEquals(Team expected, Team actual) {
        assertTeamAutoGeneratedPropertiesEquals(expected, actual);
        assertTeamAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeamAllUpdatablePropertiesEquals(Team expected, Team actual) {
        assertTeamUpdatableFieldsEquals(expected, actual);
        assertTeamUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeamAutoGeneratedPropertiesEquals(Team expected, Team actual) {
        assertThat(expected)
            .as("Verify Team auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeamUpdatableFieldsEquals(Team expected, Team actual) {
        assertThat(expected)
            .as("Verify Team relevant properties")
            .satisfies(e -> assertThat(e.getUid()).as("check uid").isEqualTo(actual.getUid()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getMobile()).as("check mobile").isEqualTo(actual.getMobile()))
            .satisfies(e -> assertThat(e.getWorkers()).as("check workers").isEqualTo(actual.getWorkers()))
            .satisfies(e -> assertThat(e.getMobility()).as("check mobility").isEqualTo(actual.getMobility()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTeamUpdatableRelationshipsEquals(Team expected, Team actual) {
        assertThat(expected)
            .as("Verify Team relationships")
            .satisfies(e -> assertThat(e.getActivity()).as("check activity").isEqualTo(actual.getActivity()))
            .satisfies(e -> assertThat(e.getOperationRoom()).as("check operationRoom").isEqualTo(actual.getOperationRoom()))
            .satisfies(e -> assertThat(e.getWarehouse()).as("check warehouse").isEqualTo(actual.getWarehouse()));
    }
}
